### ISSUE TITLE
Consider using an alternate method of code generation

### ISSUE THREAD

**Issue by expipiplus1** [folsen/opaleye-gen#6]
The string concatenation is a little hard to read.

One option would be to use template Haskell along with `pprint`. Another more lightweight option would be to use [interpolatedstring-perl6](https://hackage.haskell.org/package/interpolatedstring-perl6) to generate the code.

I'd be happy to give this a PR if you'd be interested in merging it.

**Comment by folsen** [comment]
I agree it gets kind of messy, I'd be open the more lightweight option of using interpolated strings!
